import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./../styles/globals.css";
import { cn } from "@/lib/utils";
import Providers from "./_provider/Providers";

const lato = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Simple Quicks",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-neutral-700", lato.className)}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
